Format console errors similarly to IRB
Currently, if an exception is raised during input console input sending
it will look like:

```
>> raise
!! RuntimeError
```

Now, we can show a backtrace in a similar format to IRB. It will be
cleaned up of the framework traces until the REPL for noiseless
debugging.

```
>> request.missing
NoMethodError: undefined method `missing' for #<ActionDispatch::Request:0x007fb6228197e8>
	from /web-console/test/dummy/app/controllers/exception_test_controller.rb:13:in `test_method'
```